export const moviesList = [
  {
    id: 1,
    vid:<iframe width="679" height="382" src="https://www.youtube.com/embed/nHcubNwuKFA" title="Les Éternels - Bande-annonce officielle (VF) | Marvel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `Les Éternels `,
    posterUrl: `https://upload.wikimedia.org/wikipedia/fr/5/5f/Logo_les_%C3%A9ternels.png`,
    description: `Les Éternels (Eternals) est un film de super-héros américain réalisé par Chloé Zhao, sorti en 2021.
                  `,
    rate: 3,
    
  },
  {
    id: 2,
vid: <iframe width="679" height="382" src="https://www.youtube.com/embed/XSgXWn6ffYo" title="YODHA - Official Trailer 2022 | Sidharth Malhotra | Disha Patani | Raashi Khanna (Fan-Made)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `Yodha`,
    posterUrl: `https://upload.wikimedia.org/wikipedia/en/0/02/Yodha_2022_film.jpg`,
    description: `The movie will be based on an Aeroplane hijack where a soldier helps the passenger and fight against the terrorist. `,
    rate: 2,
  },
  {
    id: 3,
vid: <iframe width="679" height="382" src="https://www.youtube.com/embed/J5SPKIxBDGs" title="THE LEDGE Trailer (2022)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `The Ledge`,
    posterUrl: `https://imgsrc.cineserie.com/2022/01/2021065.jpg?ver=1`,
    description: `Une alpiniste prise au piège sur le flanc d'une montagne combat quatre tueurs un rebord en surplomb à six mètres au-dessus d'elle. `,
    rate: 5,
  },
  {
    id: 4,
vid:<iframe width="679" height="382" src="https://www.youtube.com/embed/48J-hq3wCaA" title="PANDEMIC Trailer (2020) | Tyler Posey, Zombie Movie" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `The Pandemic`,
    posterUrl: `https://moviesandmania.com/wp-content/uploads/2022/02/after-the-pandemic-movie-film-2022-review-reviews-poster.jpg`,
    description: `A New York doctor travels with her team to Los Angeles to find survivors of a worldwide pandemic. `,
    rate: 1,
  },
  {
    id: 5,
    vid:<iframe width="560" height="315" src="https://www.youtube.com/embed/-FZ-pPFAjYY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `The Batman`,
    posterUrl: `https://www.cinetrafic.fr/images/affiches/fiche/aff_6611020200729111142.jpg`,
    description: `En 2021, l'Homme Chauve-Souris issu des comic-books édités par DC Comics revient au cinéma `,
    rate: 5,
  },
  {
    id: 6,
vid: <iframe width="679" height="382" src="https://www.youtube.com/embed/l09T87hEstI" title="Riders of Justice - Exclusive Official Trailer (2021) Mads Mikkelsen" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `Riders of Justice`,
    posterUrl: `https://www.cinetrafic.fr/images/affiches/fiche/aff_4849020220128151928.PNG`,
    description: `Film danois, Riders of justice rassemble Mads Mikkelsen (révélé par Casino Royale et Pusher II`,
    rate: 3,
  },
  {
    id: 7,
vid: <iframe width="679" height="382" src="https://www.youtube.com/embed/kzfbSuCyJXM" title="MENTEUR Bande Annonce (2022)" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,
    title: `Menteur`,
    posterUrl: `https://upload.wikimedia.org/wikipedia/fr/e/e7/Menteur_%28film%2C_2022%29.png`,
    description: `Jérôme a un grand défaut : il ment tout le temps. Lui, ne le voit pas vraiment comme un problème,.`,
    rate: 2,
  },
];
